name: Deploy PR Preview

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Node
        uses: actions/setup-node@v3

      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1.4.4
        with:
          environment: development  # Replace with your desired environment name
          deploy_target: gh-pages  # Replace with your desired target branch
          deploy_dir: ./my-website/  # Replace with the path to your Gatsby project
